### ISSUE TITLE
Use case - data feeds VR headset for 1st person replays

### ISSUE THREAD

**Issue by jpenston** [USSoccerFederation/ussf_ssac_23_soccer_gnn#1]
I am a C licensed coach but also a professional data scientist. 

I have been thinking for a while about something a lot like what you have built because I think the future of coaching involves a lot of first person replays. If you can put the player back in the moment and give them the ability to understand what they saw (and what they didn't see and why) we will undoubtedly improve decision making over time.

So, can your data be hooked up to VR such that you can create such first person replays?

**Comment by UnravelSports** [comment]
Hi!

Technically you can do this, but you need to jump through a lot of hoops.

I've made my first attempt at displaying this data in 3D which I've presented at PySport 2 days ago. You can find the repo here https://github.com/UnravelSports/rs-football-3d
