### ISSUE TITLE
Can't access your public dataset

### ISSUE THREAD

**Issue by JojiTokitou** [USSoccerFederation/ussf_ssac_23_soccer_gnn#3]
I'm a Japanese student. Sorry for the poor English.
I tried counterattack.ipynb and could not access the URL where the dataset is located.
I want to use your datasets, can you please make them accessible?
Can anybody offer me help？

**Comment by ghost** [comment]
Hi Joji, I'm sorry for not getting back to you earlier! I have added a Google Drive link that contains the same data as well as a copy of the research paper. You have to rewrite the code in the counterattack.ipynb a little bit to load the data from your machine (instead of from s3).
